version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
      - elasticsearch
    env_file:
      - .env
    environment:
      - PSQL_DB=${PSQL_DB}
      - PSQL_USERNAME=${PSQL_USERNAME}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_HOST=db
      - PSQL_PORT=${PSQL_PORT}
      - SECRET_KEY="${SECRET_KEY}"
      - ALGORITHM="${ALGORITHM}"
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "8000:8000"

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PSQL_DB}
      - POSTGRES_USER=${PSQL_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  es_data:
