"""modify models

Revision ID: 4ac8b9bb6a9f
Revises: 8e11ac7ac483
Create Date: 2025-01-14 23:07:32.600108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ac8b9bb6a9f'
down_revision: Union[str, None] = '8e11ac7ac483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('speaker', sa.String(), nullable=True))
    op.drop_column('session', 'location')
    op.drop_column('session', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('session', 'speaker')
    op.drop_column('session', 'end_time')
    op.drop_column('session', 'start_time')
    # ### end Alembic commands ###
